name: parallax-sleap

channels:
  - conda-forge
  - defaults
  - sleap
  - nvidia

dependencies:
  - git
  - python=3.8
  - pyqt>=5.15
  - pip
  - scipy
  - pyserial
  - sleap=1.3.0
  - pip:
    - pyqtgraph
    - opencv-python-headless
    - spinnaker-python
    - PyOpenGL
    - zaber-motion
    - git+https://github.com/chronopoulos/coorx
    - git+https://github.com/AllenNeuralDynamics/python-newscale@axes-on-target
    - git+https://github.com/AllenNeuralDynamics/mis-focus-controller-sw

