name: parallax

channels:
  - conda-forge
  - defaults

dependencies:
  - git
  - python=3.8
  - pyqt>=5.15
  - pip
  - scipy
  - pip:
    - pyyaml
    - pyqtgraph
    - opencv-python-headless
    - spinnaker-python
    - git+https://github.com/AllenNeuralDynamics/python-newscale
    - git+https://github.com/AllenNeuralDynamics/mis-focus-controller-sw
